In [2]:
import pandas as pd 

df = pd.read_parquet("data/processed/daily/aod_data.parquet")
df

       Station_Id        date       AOD
0               7  2025-01-01  0.376564
1               7  2025-01-02  0.410562
2               7  2025-01-03  0.472584
3               7  2025-01-04  0.294094
4               7  2025-01-05  0.805990
...           ...         ...       ...
92842         502  2025-12-25  2.108633
92843         502  2025-12-26  0.833291
92844         502  2025-12-27  1.778464
92845         502  2025-12-30  1.845761
92846         502  2025-12-31  1.043541

[92847 rows x 3 columns]

In [3]:
df = pd.read_parquet("data/processed/daily/era5_surf_data.parquet")
df

        Station_Id        date           ssrd         e            tp
0              240  2025-01-08  647046.666667 -0.000063  3.675620e-07
1              240  2025-01-09  661406.666667 -0.000062  0.000000e+00
2              240  2025-02-05  759577.333333 -0.000097  0.000000e+00
3              240  2025-02-20  789002.666667 -0.000084  9.606282e-06
4              240  2025-02-21  838326.666667 -0.000088  0.000000e+00
...            ...         ...            ...       ...           ...
146061          97  2025-07-16  308995.333333 -0.000095  1.236275e-03
146062          97  2025-07-25  512406.666667 -0.000129  9.778440e-04
146063          97  2025-07-26  410186.000000 -0.000129  1.862233e-03
146064          97  2025-08-09  417029.333333 -0.000102  1.938393e-04
146065          97  2025-08-26  592128.666667 -0.000128  2.260307e-04

[146066 rows x 5 columns]